#!/bin/sh

# Welcome to the Mariana Tek laptop uninstall script!
# Be prepared to revert your laptop (or desktop)
# to its original state before having used the
# laptop install script.

#
# Utilities
#

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

# ============================================================================
# Begin script...
# ============================================================================

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

LAPTOPRC="$HOME/.laptoprc"
ORIGINAL_ZSHRC="$HOME/.zshrc.bak"
ZSHRC="$HOME/.zshrc"
OS_VERSION=${1:-$(sw_vers -productVersion)}

#
# Cleanup existing + problematic entries (non-brew)
#


#
# Revert laptop script ZSH settings
#

if [ -f "$ORIGINAL_ZSHRC" ]; then
  rm "$ZSHRC"; cp "$ORIGINAL_ZSHRC" "$ZSHRC" && rm "$ORIGINAL_ZSHRC"
fi


#
# Remove laptop config file
#

if [ -f "$LAPTOPRC" ]; then
  rm "$LAPTOPRC"
fi

#
# Uninstall Homebrew formulae
#

## services
(brew uninstall --force 'postgresql@11' || :)

## command line utilities
(brew uninstall --force 'git' || :)
(brew uninstall --force 'wget' || :)

## zsh prompt
(brew uninstall --force 'starship' || :)

STARSHIP_CONFIG="$HOME/.config/starship.toml"
if [ -f "$STARSHIP_CONFIG" ]; then
  rm "$STARSHIP_CONFIG"
fi

#
# Install Homebrew casks
#

## Browsers
(brew uninstall --force --cask 'google-chrome' || :)

## Git
(brew uninstall --force --cask 'github' || :)

## Terminal
(brew uninstall --force --cask 'iterm2' || :)

## Editors
(brew uninstall --force --cask 'visual-studio-code' || :)

## Communication
(brew uninstall --force --cask 'slack' || :)

## Utilities
(brew uninstall --force --cask 'docker' || :)
(brew uninstall --force 'docker-compose' || :)

## Security
(brew uninstall --force --cask '1password' || :)

## Font for ZSH
(brew uninstall --force --cask 'font-meslo-lg-nerd-font' || :)

#
# Remove .laptop.local overrides
#

if [ -f $HOME/.laptop.local ]; then
  rm $HOME/.laptop.local
fi

#
# Remove editorconfig
#

if [ -f "$HOME/.editorconfig" ]; then
  rm "$HOME/.editorconfig"
fi

fancy_echo "Finished! Your shell will be automatically reloaded."

exec /bin/zsh
