" don't bother with vi compatibility
set nocompatible

" enable syntax highlighting
syntax enable
colorscheme ron

set autoindent
set autoread                                                 " reload files when changed on disk, i.e. via `git checkout`
set backspace=2                                              " Fix broken backspace in some setups
set backupcopy=yes                                           " see :help crontab
set clipboard=unnamed                                        " yank and paste with the system clipboard
set directory-=.                                             " don't store swapfiles in the current directory
set encoding=utf-8
set expandtab
set history=100                                              " remember more than 20 cmd-history
set ignorecase                                               " case-insensitive search
set incsearch                                                " search as you type
set laststatus=2                                             " always show statusline
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,trail:▫
set nobackup                                                 " don't generate swap and backup files
set nowb
set number
set ruler                                                    " show where you are
set scrolloff=3                                              " show context above/below cursorline
set shiftwidth=4
set showcmd
set smartcase                                                " case-sensitive search if any caps
set smartindent
set smarttab
set softtabstop=4
set tabstop=4
set textwidth=79

filetype plugin indent on

" Enable basic mouse behavior such as resizing buffers.
set mouse=a
if exists('$TMUX')  " Support resizing in tmux
  set ttymouse=xterm2
endif
